# Generated by Django 5.0.6 on 2024-10-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepredict", "0002_vehiclelisting_alter_userinterest_car_listing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclelisting",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("hatchback", "Hatchback"),
                    ("coupe", "Coupe"),
                ],
                default="sedan",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vehiclelisting",
            name="car_rating",
            field=models.CharField(
                choices=[
                    ("great", "Great"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("overpriced", "Overpriced"),
                ],
                default="good",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="vehiclelisting",
            name="fitness_certificate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehiclelisting",
            name="registered_city",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiclelisting",
            name="registered_state",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiclelisting",
            name="total_owners",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiclelisting",
            name="varient",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiclelisting",
            name="warranty_avail",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vehiclelisting",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("petrol", "Petrol"),
                    ("diesel", "Diesel"),
                    ("electric", "Electric"),
                    ("hybrid", "Hybrid"),
                ],
                default="petrol",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vehiclelisting",
            name="transmission",
            field=models.CharField(
                choices=[("manual", "Manual"), ("automatic", "Automatic")],
                default="manual",
                max_length=10,
            ),
        ),
    ]
