# Generated by Django 5.0.6 on 2024-11-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pricepredict",
            "0003_vehiclelisting_body_type_vehiclelisting_car_rating_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclelisting",
            name="phone_no",
            field=models.IntegerField(default=1234567890, max_length=11),
            preserve_default=False,
        ),
    ]
