# Generated by Django 5.0.6 on 2024-11-11 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepredict", "0004_vehiclelisting_phone_no"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_no", models.IntegerField(max_length=11)),
                ("company", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("kms_run", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_owners", models.IntegerField()),
                ("registered_city", models.CharField(max_length=100)),
                ("registered_state", models.CharField(max_length=100)),
                ("warranty_avail", models.BooleanField(default=False)),
                ("fitness_certificate", models.BooleanField(default=False)),
                (
                    "bike_rating",
                    models.CharField(
                        choices=[
                            ("great", "Great"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("overpriced", "Overpriced"),
                        ],
                        default="good",
                        max_length=15,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
