# Generated by Django 5.0.6 on 2024-11-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepredict", "0005_bikelisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikelisting",
            name="phone_no",
            field=models.CharField(max_length=11),
        ),
    ]
