# Generated by Django 5.0.6 on 2024-11-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepredict", "0006_alter_bikelisting_phone_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikelisting",
            name="engine_capacity",
            field=models.IntegerField(default=100, max_length=4),
            preserve_default=False,
        ),
    ]
