# Generated by Django 5.1.2 on 2024-11-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepredict", "0007_bikelisting_engine_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclelisting",
            name="phone_no",
            field=models.CharField(max_length=11),
        ),
    ]
