# Generated by Django 5.1.2 on 2024-11-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepredict", "0008_alter_vehiclelisting_phone_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikelisting",
            name="engine_capacity",
            field=models.CharField(max_length=4),
        ),
    ]
