# Generated by Django 5.1.2 on 2024-11-18 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepredict", "0009_alter_bikelisting_engine_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinterest",
            name="bike_listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pricepredict.bikelisting",
            ),
        ),
    ]
