# Generated by Django 5.1.2 on 2024-11-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepredict", "0010_userinterest_bike_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinterest",
            name="bike_listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to="pricepredict.bikelisting",
            ),
        ),
    ]
