# Generated by Django 5.1.2 on 2024-11-19 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepredict", "0012_alter_userinterest_bike_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinterest",
            name="bike_listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to="pricepredict.bikelisting",
            ),
            preserve_default=False,
        ),
    ]
